export const AUDIT_MODULES = {
  AUTHENTICATION: 'Authentication',
  ELECTION: 'Election',
  CANDIDATE: 'Candidate',
  VOTING: 'Voting',
  APPROVAL: 'Approval',
  REGISTRATION: 'Registration',
  ADMIN: 'Admin',
  OVERRIDE: 'Override',
  RESULTS: 'Results',
  SECRET_ID: 'Secret ID',
  LEGACY: 'Legacy',
};

export const AUDIT_ACTIONS = {
  USER_LOGIN: 'User login',
  USER_LOGOUT: 'User logout',
  USER_SIGNUP: 'User signup',
  PASSWORD_RESET: 'Password reset',
  EMAIL_VERIFICATION: 'Email verification',
  ELECTION_CREATED: 'Election created',
  ELECTION_UPDATED: 'Election updated',
  ELECTION_PUBLISHED: 'Election published',
  ELECTION_DELETED: 'Election deleted',
  CANDIDATE_ADDED: 'Candidate added',
  CANDIDATE_EDITED: 'Candidate edited',
  CANDIDATE_DELETED: 'Candidate deleted',
  VOTE_SUBMITTED: 'Vote submitted',
  VOTE_REJECTED: 'Vote rejected',
  SECRET_ID_VALIDATED: 'Secret ID validated',
  SECRET_ID_VALIDATION_FAILED: 'Secret ID validation failed',
  REQUEST_APPROVED: 'Election creator request approved',
  REQUEST_REJECTED: 'Election creator request rejected',
  REQUEST_SUBMITTED: 'Election creator request submitted',
  VOTER_JOINED: 'Voter joined election',
  VOTER_REMOVED: 'Voter removed',
  WAITLIST_ADDED: 'Waitlist added',
  REGISTRATION_LOCKED: 'Registration locked',
  REGISTRATION_UNLOCKED: 'Registration unlocked',
  VOTER_LIST_FINALIZED: 'Finalized voter list generated',
  RESULT_LOCKED: 'Result locked',
  RESULT_UNLOCKED: 'Result unlocked',
  MANUAL_VOTER_ADDED: 'Manual voter added',
  MANUAL_VOTER_REMOVED: 'Manual voter removed',
  MAX_VOTERS_CHANGED: 'Max voters changed',
  DASHBOARD_ACTION: 'Dashboard action',
};

export const AUDIT_PAGE_SIZE = 20;
export const OVERRIDE_PAGE_SIZE = 15;
