export const ELECTION_APPROVAL_STATUS = {
  PENDING: 'Pending',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
};

export const ELECTION_APPROVAL_STATUS_OPTIONS = [
  ELECTION_APPROVAL_STATUS.PENDING,
  ELECTION_APPROVAL_STATUS.APPROVED,
  ELECTION_APPROVAL_STATUS.REJECTED,
];
