export const VOTER_REGISTRATION_STATUS = {
  REGISTERED: 'Registered',
  WAITLISTED: 'Waitlisted',
  APPROVED: 'Approved',
  REJECTED: 'Rejected',
};

export const VOTER_REGISTRATION_STATUS_OPTIONS = [
  VOTER_REGISTRATION_STATUS.REGISTERED,
  VOTER_REGISTRATION_STATUS.WAITLISTED,
  VOTER_REGISTRATION_STATUS.APPROVED,
  VOTER_REGISTRATION_STATUS.REJECTED,
];

export const REGISTRATION_ERROR_CODES = {
  NOT_AUTHENTICATED: 'NOT_AUTHENTICATED',
  NOT_VOTER: 'NOT_VOTER',
  ELECTION_NOT_FOUND: 'ELECTION_NOT_FOUND',
  NOT_ELIGIBLE: 'NOT_ELIGIBLE',
  ELECTION_COMPLETED: 'ELECTION_COMPLETED',
  DEADLINE_PASSED: 'DEADLINE_PASSED',
  REGISTRATION_CLOSED: 'REGISTRATION_CLOSED',
  ALREADY_JOINED: 'ALREADY_JOINED',
};

export const PARTICIPATION_TERMS = [
  'One voter can vote only once',
  'False information is prohibited',
  'Secret voter ID must remain confidential',
  'Election rules must be followed',
];
